### ISSUE TITLE
Turn on GitHub actions

### ISSUE THREAD

**Issue by Emiller88** [orgzly-community/orgzly-android#4]
Might be helpful for people to install the apk.

I'd be happy to take on setting up some more elaborate actions, I've never published to fdroid though.

**Comment by amberin** [comment]
@Emiller88 I think that would be great.

I believe this should have priority, as we could gain momentum if we have an APK which people can start using. I have no experience with Actions myself, but I could have a look at it if @colonelpanic8 makes me repo admin.

**Comment by Emiller88** [comment]
Should just be [this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository)

Would it be possible for me to be added as a contributor role to the org? I'd love to get the workflow stuff setup, as that's what I can contribute. I can't work on the app itself 😬

**Comment by Emiller88** [comment]
Maybe we could start a matrix chat as well?

**Comment by amberin** [comment]
I believe @colonelpanic8 is the only one who can hand out privileges for now.

**Comment by amberin** [comment]
> Should just be [this](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository)

Yes, I just tried in my own fork and you just need to enable the defined workflows, and that's it. Then an APK is built when a PR is opened.

**Comment by colonelpanic8** [comment]
@amberin i thought I already made you an admin

**Comment by colonelpanic8** [comment]
@amberin I made you a full owner, you should be able to enable github action now.

**Comment by colonelpanic8** [comment]
> Maybe we could start a matrix chat as well?

I think that's a really good idea!

**Comment by amberin** [comment]
The existing workflow is now enabled. It should be triggered the next time someone opens a PR.

**Comment by alensiljak** [comment]
What happens to the apk? Does it get published in the Releases?

**Comment by amberin** [comment]
No, you need to the build job, and the APK can be found in the Artifacts section. (Although the job has not yet been triggered in this repo.)

**Comment by amberin** [comment]
The previously existing workflow has been enabled and works as intended.
